const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    CART_NOT_FOUND: 4,
    PRODUCT_NOT_FOUND: 5,
    OUT_OF_STOCK: 6,
    UNAUTHORIZED_ACCESS: 7,
    PRODUCT_CREATION_ERROR: 8
};

export default EErrors;